title:  Antarctica
tagline:  It is snow

# Authors documented under _data

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'Elizaveta'

google-ID: 'UA-80213386-1'

menu:
- {name: 'О сайте', url: 'about.html'}
- {name: 'Галерея', url: 'galery.html'}
- {name: 'Интересные факты', url: 'fact.html'}
- {name: 'Новости', url: 'news.html'}

social:
- {icon: 'vk', link: 'https://vk.com/1l.romanova'}
- {icon: 'envelope', link: 'mailto:romanova.ej@gmail.com'}
- {icon: 'rss-square', link: 'feed.xml'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
